import { useCallback, useEffect, useMemo, useState } from "react";
import {
  AlertTriangle,
  ArchiveRestore,
  ExternalLink,
  Eye,
  FileText,
  Info,
  Plus,
  RotateCcw,
  Save,
  ShieldCheck,
  Terminal,
  Trash2,
  X,
} from "./icons";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Textarea } from "./ui/textarea";
import { PAGE_CONTENT_WIDTH_CLASS } from "./ui/pageWidth";
import { ConfirmDialog } from "./ui/dialog";
import { useToast } from "./ui/useToast";
import { cn } from "./lib/utils";
import { parseCommandsFile } from "../helpers/commandAllowlist";
// Imported as text rather than written as a string literal, so the format's own
// documentation stays a real file of that format — diffable, and highlighted.
import DEFAULT_COMMANDS_FILE from "./commands/defaultCommands.txt?raw";
import type { CommandConfigSnapshot } from "../types/electron";

/**
 * The assistant's two command files, editable in the app.
 *
 * Two files, two editors, because they are genuinely different things:
 *
 *   - `commands.txt` is the user's own text, mostly comments, so it is edited
 *     **as text**. Parsing it into a form and re-serialising would delete every
 *     comment — and the comments are the documentation for the format.
 *   - `approved-commands.json` is generated by the app and has nothing to
 *     preserve, so it is a list.
 *
 * Strings here are plain English rather than `t()` keys, deliberately: this
 * fork's UI strings stay out of the locale bundles so a rebase does not have to
 * touch thirteen upstream files. See AGENTS.md §4 — add keys here if the fork
 * ever wants translations.
 *
 * Nothing on this screen decides what may run. The runtime reads these files
 * and `commandAllowlist.js` judges them; this only edits what the user has
 * allowed, which is the user's call either way.
 */

function AliasRow({
  names,
  command,
  capture,
}: {
  names: string[];
  command: string;
  capture: boolean;
}) {
  return (
    <li className="flex items-start gap-2.5 py-2 border-b border-foreground/4 dark:border-white/10 last:border-b-0">
      <span className="shrink-0 mt-0.5 text-foreground/35">
        {capture ? <Eye size={12} /> : <Terminal size={12} />}
      </span>
      <div className="min-w-0 flex-1">
        <p dir="auto" className="text-xs text-foreground/70 truncate">
          {names.join(", ")}
        </p>
        <p dir="auto" className="text-[11px] text-foreground/40 font-mono truncate">
          {command}
        </p>
      </div>
      {capture && (
        <span className="shrink-0 text-[10px] uppercase tracking-wide text-primary/70">
          reads output
        </span>
      )}
    </li>
  );
}

export default function CommandsView() {
  const { toast } = useToast();
  const api = window.electronAPI;

  const [snapshot, setSnapshot] = useState<CommandConfigSnapshot | null>(null);
  const [loading, setLoading] = useState(true);
  const [draft, setDraft] = useState("");
  const [savedText, setSavedText] = useState("");
  const [approved, setApproved] = useState<Array<{ command: string; capture: boolean }>>([]);
  const [newCommand, setNewCommand] = useState("");
  const [newCapture, setNewCapture] = useState(false);
  const [busy, setBusy] = useState(false);
  const [confirmOff, setConfirmOff] = useState(false);

  const load = useCallback(async () => {
    let config: CommandConfigSnapshot | undefined;
    try {
      config = await api?.getCommandConfig?.();
    } catch {
      config = undefined;
    }
    if (!config) {
      setLoading(false);
      return;
    }
    setSnapshot(config);
    setDraft(config.commandsText ?? "");
    setSavedText(config.commandsText ?? "");
    setApproved(config.approved ?? []);
    setLoading(false);
  }, [api]);

  useEffect(() => {
    void load();
  }, [load]);

  const fileExists = snapshot?.commandsText !== null && snapshot !== null;
  const dirty = draft !== savedText;
  // What the runtime will make of the draft as it is typed, so a line it cannot
  // use shows up as a count that did not move rather than as a command that
  // silently never matches. The *same* parser `localCommands` reads the file
  // with — a second implementation here would be free to disagree with it,
  // which is the one thing this count must never do.
  const parsedCount = useMemo(() => parseCommandsFile(draft).length, [draft]);

  const save = useCallback(async () => {
    if (!api?.saveCommandsFile) return;
    setBusy(true);
    try {
      const result = await api.saveCommandsFile(draft);
      if (!result || !result.ok) {
        toast({
          title: result?.error || "Could not save the file.",
          variant: "destructive",
        });
        return;
      }
      await load();
      const count = result.aliases?.length ?? 0;
      toast({
        title: `Saved. The assistant can ask for ${count} command${count === 1 ? "" : "s"} by name.`,
        variant: "success",
      });
    } catch (error) {
      toast({
        title: error instanceof Error ? error.message : "Could not save the file.",
        variant: "destructive",
      });
    } finally {
      setBusy(false);
    }
  }, [api, draft, load, toast]);

  /**
   * Puts the shipped list back in the editor.
   *
   * The same text `Create the file` offers, so there is one answer to "what does
   * this look like when it is not something I wrote" — and it is the file the
   * app ships with, comments and all, not a reduced version of it.
   *
   * It loads the draft rather than writing the file: Save stays the only path
   * by which `commands.txt` changes, which makes a mis-pressed Reset undoable
   * with Revert and shows the restored text before it takes effect. That matters
   * most in the case this exists for, where the list was already emptied and
   * saved, so Revert has nothing left to undo.
   */
  const reset = useCallback(() => {
    setDraft(DEFAULT_COMMANDS_FILE);
    toast({
      title: `Loaded the default list (${parseCommandsFile(DEFAULT_COMMANDS_FILE).length} commands) — press Save to use it.`,
      variant: "success",
    });
  }, [toast]);

  const turnOff = useCallback(async () => {
    if (!api?.deleteCommandsFile) return;
    setBusy(true);
    try {
      const result = await api.deleteCommandsFile();
      if (!result || !result.ok) {
        toast({ title: result?.error || "Could not remove the file.", variant: "destructive" });
        return;
      }
      await load();
      toast({ title: "Running commands is off.", variant: "success" });
    } catch (error) {
      toast({
        title: error instanceof Error ? error.message : "Could not remove the file.",
        variant: "destructive",
      });
    } finally {
      setBusy(false);
    }
  }, [api, load, toast]);

  const saveApproved = useCallback(
    async (next: Array<{ command: string; capture: boolean }>) => {
      if (!api?.saveApprovedCommands) return;
      setBusy(true);
      try {
        const result = await api.saveApprovedCommands(next);
        if (!result || !result.ok) {
          toast({ title: result?.error || "Could not save.", variant: "destructive" });
          return;
        }
        setApproved(result.approved ?? next);
      } catch (error) {
        toast({
          title: error instanceof Error ? error.message : "Could not save.",
          variant: "destructive",
        });
      } finally {
        setBusy(false);
      }
    },
    [api, toast]
  );

  const addApproved = useCallback(() => {
    const command = newCommand.trim();
    if (!command) return;
    // Latest wins per command, the same rule `rememberApproved` applies, so a
    // re-add updates the capture flag instead of adding a second row the
    // runtime would resolve by whichever came first.
    const next = [
      ...approved.filter((entry) => entry.command !== command),
      { command, capture: newCapture },
    ];
    setNewCommand("");
    setNewCapture(false);
    void saveApproved(next);
  }, [approved, newCapture, newCommand, saveApproved]);

  if (loading) {
    return (
      <div className={cn(PAGE_CONTENT_WIDTH_CLASS, "px-6 py-4")}>
        <p className="text-xs text-foreground/45">Loading your commands…</p>
      </div>
    );
  }

  if (!snapshot) {
    return (
      <div className={cn(PAGE_CONTENT_WIDTH_CLASS, "px-6 py-4")}>
        <p className="text-xs text-foreground/45">
          The command files could not be read. Restart the app and try again.
        </p>
      </div>
    );
  }

  const off = !fileExists;

  return (
    <div className={cn(PAGE_CONTENT_WIDTH_CLASS, "px-6 py-4 flex flex-col gap-3")}>
      <ConfirmDialog
        open={confirmOff}
        onOpenChange={setConfirmOff}
        title="Turn off running commands?"
        description="The commands file is deleted. The assistant will not be able to run anything, even with your approval — until you create the file again."
        confirmText="Turn off"
        variant="destructive"
        onConfirm={() => void turnOff()}
      />

      <p className="text-xs text-foreground/45 leading-relaxed">
        These are the two files behind <span className="text-foreground/70">run_command</span> — the
        assistant opening apps, running programs, and reading back what they print. Everything here
        is your own text; nothing is sent to a model.
      </p>

      {/* ─── Commands the assistant may run ─── */}
      <div className="rounded-md border border-foreground/8 dark:border-white/10 bg-foreground/[0.02] dark:bg-white/[0.03] px-4 py-3">
        <div className="flex items-center justify-between gap-3">
          <div className="flex items-center gap-2 min-w-0">
            <FileText size={12} className="text-foreground/35 shrink-0" />
            <span className="text-xs font-semibold text-foreground/70">Commands</span>
            {off ? (
              <span className="text-[10px] uppercase tracking-wide text-amber-600 dark:text-amber-400">
                off
              </span>
            ) : (
              <span className="text-[11px] text-foreground/40">
                {parsedCount} {parsedCount === 1 ? "command" : "commands"}
              </span>
            )}
          </div>
          <button
            type="button"
            onClick={() => void api?.revealCommandConfig?.("commands")}
            className="flex items-center gap-1.5 text-[11px] text-foreground/45 hover:text-foreground/70 transition-colors shrink-0"
          >
            <ExternalLink size={11} />
            Show in folder
          </button>
        </div>

        <p className="text-[11px] text-foreground/40 mt-1 font-mono truncate">
          {snapshot.commandsFile}
        </p>

        {off && !dirty ? (
          <div className="mt-3 rounded-md border border-foreground/8 dark:border-white/10 px-3 py-3">
            <div className="flex items-start gap-2.5">
              <AlertTriangle
                size={13}
                className="text-amber-600 dark:text-amber-400 mt-0.5 shrink-0"
              />
              <div className="min-w-0">
                <p className="text-xs text-foreground/70">The commands file does not exist.</p>
                <p className="text-[11px] text-foreground/45 mt-0.5 leading-relaxed">
                  Without it the feature is off: the assistant cannot run anything, even after
                  asking you. Create it to switch it back on.
                </p>
                <div className="flex items-center gap-2 mt-2.5">
                  <Button size="sm" className="h-7 text-xs" onClick={reset}>
                    <Plus size={12} />
                    Create the file
                  </Button>
                  <Button
                    variant="ghost"
                    size="sm"
                    className="h-7 text-xs"
                    disabled={busy}
                    onClick={reset}
                    title="Loads the list of commands this app ships with"
                  >
                    <RotateCcw size={12} />
                    Reset
                  </Button>
                  <Button
                    variant="ghost"
                    size="sm"
                    className="h-7 text-xs"
                    onClick={() => void api?.revealCommandConfig?.("commands")}
                  >
                    Open the folder
                  </Button>
                </div>
              </div>
            </div>
          </div>
        ) : (
          <>
            <Textarea
              dir="auto"
              spellCheck={false}
              value={draft}
              onChange={(event) => setDraft(event.target.value)}
              rows={14}
              className="mt-2.5 font-mono text-[11px] leading-relaxed min-h-[220px] resize-y"
            />

            <div className="flex items-center justify-between gap-3 mt-2">
              <p className="text-[11px] text-foreground/40 leading-relaxed">
                <span className="font-mono">name = command</span> per line,{" "}
                <span className="font-mono">#</span> for comments. A{" "}
                <span className="font-mono">!</span> in front makes the assistant read back what the
                command printed. Clearing the list by accident is recoverable:{" "}
                <span className="text-foreground/60">Reset</span> puts the shipped list back, so an
                accidental wipe is not the end of it.
              </p>
              <div className="flex items-center gap-2 shrink-0">
                {/* Distinct from Revert next to it: Revert throws away unsaved
                    edits, Reset brings back a version that was saved and then
                    lost. The wipe this exists for is usually already saved, so
                    by then Revert has nothing left to undo. */}
                <Button
                  variant="ghost"
                  size="sm"
                  className="h-7 text-xs"
                  disabled={busy}
                  onClick={reset}
                  title="Loads the list of commands this app ships with, back into the editor"
                >
                  <ArchiveRestore size={12} />
                  Reset
                </Button>
                {dirty && (
                  <Button
                    variant="ghost"
                    size="sm"
                    className="h-7 text-xs"
                    disabled={busy}
                    onClick={() => setDraft(savedText)}
                  >
                    <RotateCcw size={12} />
                    Revert
                  </Button>
                )}
                {!off && (
                  <Button
                    variant="ghost"
                    size="sm"
                    className="h-7 text-xs text-foreground/45 hover:text-destructive/80"
                    disabled={busy}
                    onClick={() => setConfirmOff(true)}
                  >
                    <Trash2 size={12} />
                    Turn off
                  </Button>
                )}
                <Button
                  size="sm"
                  className="h-7 text-xs"
                  disabled={busy || !dirty}
                  onClick={() => void save()}
                >
                  <Save size={12} />
                  Save
                </Button>
              </div>
            </div>
          </>
        )}
      </div>

      {/* ─── What the file currently gives the assistant ─── */}
      {!off && snapshot.aliases.length > 0 && (
        <div className="rounded-md border border-foreground/8 dark:border-white/10 bg-foreground/[0.02] dark:bg-white/[0.03] px-4 py-3">
          <div className="flex items-center gap-2">
            <ShieldCheck size={12} className="text-foreground/35 shrink-0" />
            <span className="text-xs font-semibold text-foreground/70">
              What the assistant can ask for
            </span>
          </div>
          <p className="text-[11px] text-foreground/40 mt-1 leading-relaxed">
            These run with no confirmation. Anything carrying arguments with shell syntax (
            <span className="font-mono">;</span> <span className="font-mono">|</span>{" "}
            <span className="font-mono">$(</span>) is sent to the approval dialog instead.
          </p>
          <ul className="mt-2">
            {snapshot.aliases.map((alias) => (
              <AliasRow
                key={`${alias.names.join(",")}=${alias.command}`}
                names={alias.names}
                command={alias.command}
                capture={alias.capture}
              />
            ))}
          </ul>
        </div>
      )}

      {/* ─── Approved one-off commands ─── */}
      <div className="rounded-md border border-foreground/8 dark:border-white/10 bg-foreground/[0.02] dark:bg-white/[0.03] px-4 py-3">
        <div className="flex items-center justify-between gap-3">
          <div className="flex items-center gap-2 min-w-0">
            <ShieldCheck size={12} className="text-foreground/35 shrink-0" />
            <span className="text-xs font-semibold text-foreground/70">Approved commands</span>
            <span className="text-[11px] text-foreground/40">{approved.length}</span>
          </div>
          <button
            type="button"
            onClick={() => void api?.revealCommandConfig?.("approved")}
            className="flex items-center gap-1.5 text-[11px] text-foreground/45 hover:text-foreground/70 transition-colors shrink-0"
          >
            <ExternalLink size={11} />
            Show in folder
          </button>
        </div>

        <p className="text-[11px] text-foreground/40 mt-1 leading-relaxed">
          Commands you approved from the dialog — or add one here. Each runs with no confirmation
          from now on, exactly as written.
        </p>

        <div className="mt-2.5 flex items-center gap-2">
          <Input
            dir="auto"
            value={newCommand}
            onChange={(event) => setNewCommand(event.target.value)}
            onKeyDown={(event) => {
              if (event.key === "Enter") addApproved();
            }}
            placeholder="e.g. docker ps"
            className="h-7 text-xs font-mono flex-1"
          />
          <label className="flex items-center gap-1.5 text-[11px] text-foreground/50 shrink-0 cursor-pointer">
            <input
              type="checkbox"
              checked={newCapture}
              onChange={(event) => setNewCapture(event.target.checked)}
              className="accent-primary"
            />
            read output
          </label>
          <Button
            size="sm"
            className="h-7 text-xs shrink-0"
            disabled={busy || !newCommand.trim()}
            onClick={addApproved}
          >
            <Plus size={12} />
            Add
          </Button>
        </div>

        {approved.length > 0 ? (
          <ul className="mt-2">
            {approved.map((entry) => (
              <li
                key={entry.command}
                className="group flex items-center gap-2 h-9 border-b border-foreground/4 dark:border-white/10 last:border-b-0"
              >
                <span
                  className="flex-1 min-w-0 text-xs font-mono text-foreground/60 truncate"
                  dir="auto"
                >
                  {entry.command}
                </span>
                <label className="flex items-center gap-1.5 text-[11px] text-foreground/45 shrink-0 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={entry.capture}
                    disabled={busy}
                    onChange={() =>
                      void saveApproved(
                        approved.map((item) =>
                          item.command === entry.command
                            ? { ...item, capture: !item.capture }
                            : item
                        )
                      )
                    }
                    className="accent-primary"
                  />
                  read output
                </label>
                <button
                  type="button"
                  aria-label={`Remove ${entry.command}`}
                  disabled={busy}
                  onClick={() =>
                    void saveApproved(approved.filter((item) => item.command !== entry.command))
                  }
                  className="shrink-0 p-1 text-foreground/35 hover:text-destructive/80 transition-colors opacity-0 group-hover:opacity-100"
                >
                  <X size={11} strokeWidth={2} />
                </button>
              </li>
            ))}
          </ul>
        ) : (
          <p className="mt-3 py-3 text-[11px] text-foreground/35 text-center">
            Nothing approved yet. Commands you choose “Run and remember” for will appear here.
          </p>
        )}
      </div>

      <div className="flex items-start gap-2 px-1">
        <Info size={12} className="text-foreground/30 mt-0.5 shrink-0" />
        <p className="text-[11px] text-foreground/40 leading-relaxed">
          A name in the commands file is standing permission: anything that reaches the model — a
          web page, a note, a screenshot — can ask for one by name and get it unprompted, arguments
          included. Keep them to things whose worst case is opening the wrong thing, and never alias
          a general-purpose tool like <span className="font-mono">git</span> or{" "}
          <span className="font-mono">docker</span> on its own.
        </p>
      </div>
    </div>
  );
}
